version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: "root"

  springApp:
    build:
      context: .
    image: backend
    ports:
      - "8080:8080"
    environment:
      - amazon.dynamodb.endpoint=http://dynamodb-local:8000
      - SECRET_KEY=${SECRET_KEY}
